library(tidyverse)
library(stringr)
library(rsdmx)
library(writexl)

#OECD
OECD <- read_csv("1 - Data/1 - Raw/Global/OECD.csv")

variables <- unique(OECD[,c("TRANSACTION", "Transaction", "UNIT_MEASURE", "Unit of measure", "PRICE_BASE", "Price base" )]) %>%
  mutate(acronym = paste(TRANSACTION, UNIT_MEASURE, PRICE_BASE, sep = "_"),
         description = paste(.$"Transaction", .$"Unit of measure", .$"Price base", sep = ", ")) %>%
  select(acronym, description)

sectors <- unique(OECD[, c("ACTIVITY", "Economic activity")]) %>%
  filter(str_length(ACTIVITY) == 1 | ACTIVITY == "_T")

#BIH
url <- "https://bhas.gov.ba/data/Publikacije/IMF/NAG_Bosnia%20and%20Herzegovina.xml"
sdmx_data <- readSDMX(url)
series <- as.data.frame(sdmx_data)

test <- series %>%
  filter(TIME_PERIOD == 2016 & OBS_VALUE > 1865000 & OBS_VALUE < 1867000) #Testing if matches PDF
sort(unique(series$TIME_PERIOD))

write_xlsx(series, "1 - Data/1 - Raw/BIH_national_2006-2023.xlsx")

#BHR
data <- read_csv("1 - Data/1 - Raw/BHR_national_2011-2022.csv")

#CIV
url <- "https://nso-cotedivoire.opendataforafrica.org/api/1.0/sdmx/get?id=vnbyidc&altCode=SDMX-Code"
sdmx_data <- readSDMX(url)
series <- as.data.frame(sdmx_data)

test <- series %>%
  filter(str_detect(.$"SDMX-CODE_INDICATOR", "NGDPVA_ISIC4"))
sort(unique(test$NOM_INDICATOR))

write_xlsx(series, "1 - Data/1 - Raw/CIV_national_2016-2023.xlsx")

#UN

UN_curr <- read_csv("1 - Data/1 - Raw/Global/UNdata_current.csv") 
UN_const <- read_csv("1 - Data/1 - Raw/Global/UNdata_constant.csv")

sectors <- unique(UN_curr[,c("SNA93 Item Code","Item")])

#KWT
url <- "https://www.cbk.gov.kw/en/redirects/download?dfile=18IS9zhKOokg9ShBGVM7vXKVn9gmSW~SCaU~0b4q5CgYqynHor61s8MzLQrrkQ4=&cext=xml&esIndex=autogenerated"
data <- as.data.frame(readSDMX(url))

#QAT
url<- "https://www.psa.gov.qa/en/statistics/NSDP/NAG_Qatar.xml"
data <- as.data.frame(readSDMX(url))
write.xlsx(data, "1 - Data/1 - Raw/QAT_national_2009-2023.xlsx")

#XKX
url <- "https://ask.rks-gov.net/SDMX/na/na.xml"
data <- as.data.frame(readSDMX(url))
write.xlsx(data, "1 - Data/1 - Raw/XKX_national_2010-2023.xlsx")

#KHM
url <- "https://www.nbc.gov.kh/download_files/nsdp/XML/NAG_Cambodia.xml"
data <- as.data.frame(readSDMX(url))
write.xlsx(data, "1 - Data/1 - Raw/KHM_national_1993-2022.xlsx")

#PAK
url <- "https://www.pbs.gov.pk/sites/default/files/nsdp/NAG.xml"
data <- as.data.frame(readSDMX(url))
write_xlsx(data, "1 - Data/1 - Raw/PAK_national_2000-2023.xlsx")
